name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    name: "Tests on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10", "12", "14", "16"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build
      - run: yarn test
